name: Build iOS App
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild clean archive \
            -project "ReflectiveClothes.xcodeproj" \
            -scheme "ReflectiveClothes" \
            -archivePath ./output.xcarchive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Export IPA
        run: |
          mkdir -p Payload
          cp -r ./output.xcarchive/Products/Applications/ReflectiveClothes.app Payload/
          zip -r ReflectiveClothes.ipa Payload

      - uses: actions/upload-artifact@v4
        with:
          name: ReflectiveClothesIPA
          path: "ReflectiveClothes.ipa"
