name: Build iOS App
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild archive -project "ReflectiveClothes.xcodeproj" -scheme "ReflectiveClothes" -archivePath output APPLICATION_EXTENSION_BUILD_ALLOWED=NO CODE_SIGNING_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Make IPA
        run: |
          mkdir Payload
          cp -r output.xcarchive/Products/Applications/ReflectiveClothes.app Payload/
          zip -r ReflectiveClothes.ipa Payload

      - uses: actions/upload-artifact@v4
        with:
          name: MyIPA
          path: "ReflectiveClothes.ipa"
